---

- name: Make sure Debian managed packages are not installed
  ansible.builtin.apt:
    name:
      - "docker.io"
      - "docker-compose"
      - "docker-doc"
      - "podman-docker"
      - "containerd"
      - "runc"
    update_cache: no
    state: absent

- name: Install requirements
  ansible.builtin.apt:
    name:
      - "ca-certificates"
      - "gnupg"
    update_cache: yes
    state: latest

- name: Add docker repository key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    update_cache: yes
    state: present
