---

- name: Make sure Rocky managed packages are not installed
  ansible.builtin.dnf:
    name:
      - "docker"
      - "docker-client"
      - "docker-client-latest"
      - "docker-common"
      - "docker-latest"
      - "docker-latest-logrotate"
      - "docker-logrotate"
      - "docker-engine"
    update_cache: no
    state: absent

- name: Add docker repository
  community.general.ini_file:
    path: /etc/yum.repos.d/docker.repo
    section: docker-ce-stable
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: yes
  loop:
    - { "option": "name", "value": "Docker CE Stable - $basearch" }
    - { "option": "baseurl", "value": "https://download.docker.com/linux/centos/$releasever/$basearch/stable" }
    - { "option": "enabled", "value": "1" }
    - { "option": "gpgcheck", "value": "1" }
    - { "option": "gpgkey", "value": "https://download.docker.com/linux/centos/gpg" }
